<MyLayout>
    do_default_tab: False

    TabbedPanelItem:
        text: 'Tab 1'
        Label:
            text: 'Hello World'

    TabbedPanelItem:
        text: 'Tab 2'
        BoxLayout:
            Label:
                text: 'Here I am'
            Button:
                text: 'Button that does nothing'

    TabbedPanelItem:
        text: 'IMAGE'
        Image:
            source: "images/ChrisWindowMike.JPG"
            allow_stretch: False
        